root = "."
tmp_dir = "scripts/.tmp/air"

[build]
cmd = "true"
full_bin = "dlv --headless=true --listen=:2345 --api-version=2 --accept-multiclient debug ./cmd/app --continue --output scripts/.tmp/debug"
include_ext = ["go", "yaml"]
exclude_dir = ["assets", "tmp", "testdata", "vendor"]
include_dir = []
include_file = []
exclude_file = []
exclude_regex = ["_test.go"]
exclude_unchanged = false
follow_symlink = false
log = "air.log"
poll = true # windows
poll_interval = 500 # ms
delay = 0 # ms
stop_on_error = true
send_interrupt = false
kill_delay = 500 # nanosecond
rerun = false
rerun_delay = 500

[log]
time = false
main_only = false

[color]
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[misc]
clean_on_exit = true

[screen]
clear_on_rebuild = true
keep_scroll = true
