services:
  go-project-template:
    container_name: go-project-template
    build:
      context: ..
      dockerfile: ../build/package/image/dev.Dockerfile
    volumes:
      - ../:/app
    ports:
      - "2345:2345"
